# Generated by Django 2.2 on 2020-11-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0017_auto_20201105_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(help_text='Department of Study', max_length=50),
        ),
    ]
